service: aws-lambda-perl

frameworkVersion: ">=1.34.0 <2.0.0"

provider:
  name: aws
  region: ${opt:region, 'eu-central-1'}
  stage: prod

layers:
  perl:
    package:
      artifact: perl-layer.zip

resources:
  Outputs:
    PerlLayerExport:
      Value:
        Ref: PerlLambdaLayer
      Export:
        Name: PerlLambdaLayer

package:
  exclude:
    - ./**
