# aws-lambda-perl
#
# Serverless config to deploy this layer to AWS.

service: aws-lambda-perl

frameworkVersion: ">=1.34.0 <2.0.0"

provider:
  name: aws
  region: ${opt:region, 'eu-central-1'}
  stage: prod

layers:
  perl:
    package:
      artifact: perl-${opt:perl_version, '5.30.0'}-layer.zip

resources:
  Outputs:
    PerlLayerExport:
      Value:
        Ref: PerlLayerExport
      Export:
        Name: PerlLayerExport

package:
  exclude:
    - ./**
