version: 2.1
executors:
  docker-builder:
    environment:
      IMAGE_NAME: aws-lambda-perl
      PERL_VERSION: 5.30.0
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-builder
    steps:
      - checkout
      - setup_remote_docker
      - run: curl -LO https://www.cpan.org/src/5.0/perl-${PERL_VERSION}.tar.gz
      - run: docker build -t ${IMAGE_NAME}:latest .
      - run: docker save -o image.tar ${IMAGE_NAME}
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-to-dockerhub:
    executor: docker-builder
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run: docker load -i /tmp/workspace/image.tar
      - run: |
          echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin
          IMAGE_TAG=${CIRCLE_TAG/v/''}
          docker tag ${IMAGE_NAME}:latest ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:latest
          docker tag ${IMAGE_NAME}:latest ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG}
          docker push ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:latest
          docker push ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG}
  publish-to-awslambda:
    docker:
      - image: ericnchen/aws-lambda-perl:latest
    steps:
      - checkout
      - run: npm install -g serverless
      - run: cd /opt && zip -qry -9 /tmp/perl-layer.zip .
      - run: cp /tmp/perl-layer.zip .
      - run: serverless deploy
workflows:
  version: 2
  build-dev:
    jobs:
      - build:
          filters:
            branches:
              only: dev
  build-and-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish-to-dockerhub:
          context: dockerhub/ericnchen
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish-to-awslambda:
          requires:
            - build
            - publish-to-dockerhub
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/